### ISSUE TITLE
error: undefined reference to `unlisten_device_by_hash_element'

### ISSUE THREAD

**Issue by fantasmashy** [gentoo-root/jacklistener#9]
path_to_jacklistener/main.c:218: undefined reference to `unlisten_device_by_hash_element'

i just moved `#ifdef ENABLE_UDEV` (line75) down the function definition of `unlisten_device_by_hash_element' in the watchdevs.c file and thats seems to make it work.

**Comment by gentoo-root** [comment]
Thanks for spotting it!

I also noticed that unlisten_device_by_hash_element is called during an unsafe iteration of the list. HASH_ITER should be used instead (otherwise it's use-after-free). Let me patch it up.

**Comment by gentoo-root** [comment]
Could you give it a spin? Please tell me if this works for you:

https://github.com/gentoo-root/jacklistener/commits/noudev-fixes/

BTW, out of curiosity, why don't you use ENABLE_UDEV?

**Comment by fantasmashy** [comment]
> BTW, out of curiosity, why don't you use ENABLE_UDEV?

i don't know what that is.

> Could you give it a spin? Please tell me if this works for you:

yup, the daemon is active and running.
...and i don't know how to use it.

**Comment by gentoo-root** [comment]
> > BTW, out of curiosity, why don't you use ENABLE_UDEV?
> i don't know what that is.

Oh, I see, it seems to be poorly documented... You can pass `--enable-udev` to the `./configure` script, and you can start the daemon with the `--udev` flag, instead of passing all the devices manually (it happens automatically if you use the systemd unit). This way, it supports hotplug of audio devices (e.g., if you plug in a USB headset or the daemon is started too early).

> ...and i don't know how to use it.

You can use it with [jackeventcmd](https://github.com/gentoo-root/jackeventcmd) which runs with your user's privileges and allows to show notifications and pause music players (or run any other custom action that you configure on jack events).

Generally, it provides a D-Bus interface that is available to other applications.
